<?php

namespace GarderieBundle\Repository;

/**
 * responsableLegalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class responsableLegalRepository extends \Doctrine\ORM\EntityRepository
{
}
