<?php

namespace GarderieBundle\Repository;

/**
 * tarifRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class tarifRepository extends \Doctrine\ORM\EntityRepository
{
}
